// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXvPh53K1_BbK_H3oZxlXpXK5yOTQ0jw4',
    appId: '1:29102015061:web:b4454114797ef31f518adc',
    messagingSenderId: '29102015061',
    projectId: 'smartgavali',
    authDomain: 'smartgavali.firebaseapp.com',
    storageBucket: 'smartgavali.firebasestorage.app',
    measurementId: 'G-2QKTJP7W2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJRspLNs633rEHCWNgyjpeFr0yIWy0S0',
    appId: '1:29102015061:android:3260142c2834e5cd518adc',
    messagingSenderId: '29102015061',
    projectId: 'smartgavali',
    storageBucket: 'smartgavali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4insoc7ERhiZsJ_3ThbrUGrJSQmq8Yw',
    appId: '1:29102015061:ios:c3bf83b2ba62f8d7518adc',
    messagingSenderId: '29102015061',
    projectId: 'smartgavali',
    storageBucket: 'smartgavali.firebasestorage.app',
    iosBundleId: 'com.smartgawali.smartGawali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH4insoc7ERhiZsJ_3ThbrUGrJSQmq8Yw',
    appId: '1:29102015061:ios:c3bf83b2ba62f8d7518adc',
    messagingSenderId: '29102015061',
    projectId: 'smartgavali',
    storageBucket: 'smartgavali.firebasestorage.app',
    iosBundleId: 'com.smartgawali.smartGawali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXvPh53K1_BbK_H3oZxlXpXK5yOTQ0jw4',
    appId: '1:29102015061:web:9e8a97f07a8b25c9518adc',
    messagingSenderId: '29102015061',
    projectId: 'smartgavali',
    authDomain: 'smartgavali.firebaseapp.com',
    storageBucket: 'smartgavali.firebasestorage.app',
    measurementId: 'G-SQ0590BEER',
  );
}
